### ISSUE TITLE
Start button location

### ISSUE THREAD

**Issue by sf467** [ramensoftware/windows-11-taskbar-styling-guide#10]
For example, the Start button is placed on the far left, but the general taskbar icon is still displayed in the center.

**Comment by 70V07** [comment]
**also is better this... but not possibile at moment:**

- left or right: clock and calendar and feed
- center: start button menu and apps
- right or left: tray icons

_and OBV remove the useless Windows-widgets-feeds (I already removed)_

**Comment by m417z** [comment]
Some relevant ideas were discussed here:
https://github.com/ramensoftware/windhawk-mods/discussions/679

**Comment by m417z** [comment]
I created a mod for placing the start button on the left: [Start button always on the left](https://windhawk.net/mods/taskbar-start-button-position).
It has limitations (see the mod description), but generally it works.

![image](https://github.com/user-attachments/assets/03dd0de3-c390-4f45-a83d-c800ac98c9ac)
