### ISSUE TITLE
Reposition trafic monitor indicator from right to left

### ISSUE THREAD

**Issue by helix-77** [ramensoftware/windows-11-taskbar-styling-guide#109]
I am using traffic monitor and want to reposition it to the left side instead. How can i do that?

![Screenshot 2024-09-29 182603](https://github.com/user-attachments/assets/08505261-9656-47d3-b489-c91c94d48f64)

**Comment by m417z** [comment]
What's that traffic monitor indicator? Is it managed by another third-party program? You probably need to look for a solution there.

**Comment by helix-77** [comment]
[This one](https://github.com/zhongyang219/TrafficMonitor)

**Comment by m417z** [comment]
At least from the screenshot here, looks like there's an option for that:
https://github.com/zhongyang219/TrafficMonitor/issues/1412

In any case, it doesn't seem related to Windhawk or the taskbar styling mod as it's managed by another program.

**Comment by helix-77** [comment]
Yes, found it. Thanks
