### ISSUE TITLE
[Suggestion/Question] Is it possible to change the taskbar when the desktop is focued?

### ISSUE THREAD

**Issue by Zacgamingpro1234** [ramensoftware/windows-11-taskbar-styling-guide#114]
I would like to know if you can change the taskbar when the desktop is focused. If this is possible I would like to make the taskbar clear when the desktop is selected.

**Comment by m417z** [comment]
Not sure what "desktop is selected" means. There's the following mod which can change the taskbar background when windows are maximized: [Taskbar Background Helper](https://windhawk.net/mods/taskbar-background-helper).

**Comment by Zacgamingpro1234** [comment]
Oh I think that might do it, thanks! I meant to say when there is no maximized tab (the desktop is technically visible) the taskbar should change.
