### ISSUE TITLE
My taskbar have white lines

### ISSUE THREAD

**Issue by presian0** [ramensoftware/windows-11-taskbar-styling-guide#115]
![Screenshot_1](https://github.com/user-attachments/assets/ca732566-6191-4def-94cf-5431e40f1a14)

**Comment by m417z** [comment]
Looks like this issue: https://github.com/ramensoftware/windhawk-mods/issues/1028, unfortunately I'm not sure what I can do without a way to reproduce it. Perhaps you can play with styles or with UWPSpy to try to find what causes it or what's that box.

**Comment by presian0** [comment]
ok i'm gonna see if i can
