### ISSUE TITLE
Language Switcher Font Family Styling

### ISSUE THREAD

**Issue by Josephwonguk** [ramensoftware/windows-11-taskbar-styling-guide#117]
Hi there,
I'm attempting to change the font of the language switcher in the System Tray - I've found that it relies on:
Name: SystemTray.AdaptiveTextBlock
Class: LanguageInnerTextBlock
I know very little about the XAML, but I can't seem to get it to change.
Any assistance would be great.

![Screenshot 2024-10-13 214530](https://github.com/user-attachments/assets/a7c357ed-e8c3-4a0a-aee1-e11e6db009c1)

**Comment by bbmaster123** [comment]
You're on the right track, that is the correct target.

see here for more detail about how to use UWPspy, and let me know if anything needs further explanation
[https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md](https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md)

**Comment by Josephwonguk** [comment]
Great, got it working!
I used this code:
Target: SystemTray.LanguageTextIconContent > Windows.UI.Xaml.Controls.Grid#ContainerGrid > SystemTray.AdaptiveTextBlock#LanguageInnerTextBlock > Windows.UI.Xaml.Controls.TextBlock#InnerTextBlock
Value: FontFamily=<Enter Font Name>

I don't know if it's the most simple, but it worked!
