### ISSUE TITLE
How to set minimum width of empty space on task bar?

### ISSUE THREAD

**Issue by bege10** [ramensoftware/windows-11-taskbar-styling-guide#118]
I want to use the Windhawk mod "Click on empty taskbar space". When the taskbar is full there is very little empty space so that it is very difficult to hit that space. How can I set a minimum width?

BTW, which process must I select in UWPspy to examine the task bar?

**Comment by m417z** [comment]
> BTW, which process must I select in UWPspy to examine the task bar?

Run UWPSpy, move your mouse over the target and press Ctrl+D. The process will be selected in the list.

In the case of the taskbar, it's explorer.exe.

**Comment by bege10** [comment]
I thought so. But I get these errors
![Screenshot_011](https://github.com/user-attachments/assets/3d02b473-cd3e-4cdc-8866-50f97e74ea2f)
![Screenshot_012](https://github.com/user-attachments/assets/2968138b-dc51-4b6e-b93f-93cbb26f0363)

**Comment by m417z** [comment]
Are you using other customization tools, such as ExplorerPatcher or StartAllBack?

**Comment by bege10** [comment]
Yes, ExplorerPatcher.

**Comment by m417z** [comment]
This mod only works with the native Windows 11 taskbar. You can switch to it in ExplorerPatcher's settings, otherwise the mod won't work.
