### ISSUE TITLE
Customization request: Squircle Theme with Translucent Effect

### ISSUE THREAD

**Issue by DreadBo1** [ramensoftware/windows-11-taskbar-styling-guide#129]
Is there a way to apply a "Squircle" theme to the taskbar with a translucent effect? Thank you.

**Comment by SandTechStuff** [comment]
The Squircle theme already uses Acrylic transparency. Do you mean you want the taskbar to be translucent instead of completely see through?

**Comment by DreadBo1** [comment]
i meant this parts of the taskbar.
![Screenshot 2024-11-05 172532](https://github.com/user-attachments/assets/1bab941e-1a1f-40ae-83e2-41edb93a7210)


> The Squircle theme already uses Acrylic transparency. Do you mean you want the taskbar to be translucent instead of completely see through?

**Comment by bbmaster123** [comment]
Target: Rectangle#BackgroundFill
Style: Fill=Color

Please see the styling guide for more info:
[styling guide](https://github.com/ramensoftware/windows-11-taskbar-styling-guide)

Let me know if you need further help, cheers :)

**Comment by DreadBo1** [comment]
> Target: Rectangle#BackgroundFill Style: Fill=Color
> 
> Please see the styling guide for more info: [styling guide](https://github.com/ramensoftware/windows-11-taskbar-styling-guide)
> 
> Let me know if you need further help, cheers :)

Thank you! Apologies for not clarifying in my previous comments I was referring to "Task list labels." Is there an option to apply an acrylic transparency or translucent effect to them?

**Comment by bbmaster123** [comment]
ah gotcha
yes you can do that too, see [here](https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md) which is linked in the styling guide to find what elements you can style, their class/name, and which properties can be modified
See the colors section near the bottom of the guide for how to set an acrylic background

If you have any trouble finding the target or setting your style let me know!

**Comment by DreadBo1** [comment]
> ah gotcha yes you can do that too, see [here](https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md) which is linked in the styling guide to find what elements you can style, their class/name, and which properties can be modified See the colors section near the bottom of the guide for how to set an acrylic background
> 
> If you have any trouble finding the target or setting your style let me know!

Tysm! I found it! ❤️
In case anyone wants to make the taskbar completely transparent:

Target: Rectangle#BackgroundFill
Style: Fill=Transparent

Target: Rectangle#BackgroundStroke
Style: Fill=Transparent
