### ISSUE TITLE
taskbar still isnt floating

### ISSUE THREAD

**Issue by nikvl77** [ramensoftware/windows-11-taskbar-styling-guide#130]
configured the taskbar as stated but for some reason it only made the edges round but didnt make the taskbar float

![{A00F2AAB-2EAA-4732-BB9D-25C94FD52CC1}](https://github.com/user-attachments/assets/072318f5-7de8-4a80-b3f9-9b9104e25f10)

**Comment by bbmaster123** [comment]
Can I see your theme code?
Which tweaks did you apply, just floating tb or border too?

My initial assumption is you are using the margins for no floating taskbar which is `Margin=0,0,0,-2` rather than `Margin=0,1,0,3`

**Comment by nikvl77** [comment]
I applied both tweaks in the order on the instructions page, not sure what to change.
![windhawk 1](https://github.com/user-attachments/assets/9ed15fb3-4ea3-44db-b978-a121e9a90471)
![windhawk 2](https://github.com/user-attachments/assets/7a2b0fa6-aadb-485c-aa63-81ff212e6426)
![windhawk 3](https://github.com/user-attachments/assets/4e922e01-1da4-4e39-8374-73225f48bde5)
![windhawk 4](https://github.com/user-attachments/assets/5c72dc59-d4fe-4cfd-98d3-ce32eeb252b1)
![windhawk 5](https://github.com/user-attachments/assets/e6981c11-51a4-4017-a2f5-4e96ede781cd)

**Comment by bbmaster123** [comment]
aha yup, that explains it
See how you have `Grid#SystemTrayFrameGrid` twice with two different margins?
What that means is that the mod first sets `Grid#SystemTrayFrameGrid` to `Margin=8,1,8,3`, then later on, it sets `Grid#SystemTrayFrameGrid` to `Margin=0,0,0,-2` overwriting the previously set margins.

Maybe I should make that step a little more clear in the docklike readme, but its saying only apply this style if you have not applied the other style, which you did, so you should skip that step
![image](https://github.com/user-attachments/assets/9d0a60b9-ddb9-49c4-9de7-efc43b9a2546)

Anyway, to fix the issue, just remove the second instance of `Grid#SystemTrayFrameGrid` and you should be good to go :)

**Comment by nikvl77** [comment]
Just a quick one, how do you move the task bar up a few pixels as I would like the gap to be a little bigger?

**Comment by bbmaster123** [comment]
You can adjust `Taskbar.TaskbarFrame#TaskbarFrame > Grid#RootGrid` margins slightly to increase the bottom gap
For example, try `Margin=0,1,0,5`

In order, those numbers adjust left, top, right, bottom. You can also use non integer values or negative values (ex. Margin=0,-1.5,0,5)

**Comment by nikvl77** [comment]
Thanks a lot🙏🏻
