### ISSUE TITLE
How to change mouse over effect?

### ISSUE THREAD

**Issue by miomate** [ramensoftware/windows-11-taskbar-styling-guide#137]
Thank you very much for this amazing tool.

I am using RosePine und don't like the yello-wish rectangle that appears if I mouse over a label in the taskbar.
With which setting could I change the color?

Thanks you.

**Comment by bbmaster123** [comment]
```
Target: 
Taskbar.TaskListLabeledButtonPanel@CommonStates > Rectangle#RunningIndicator

Styles:
Stroke@InactivePointerOver=#ebbcba
Stroke@InactivePressed=#ebbcba
Stroke@ActiveNormal=#ebbcba
Stroke@ActivePointerOver=#ebbcba
Stroke@ActivePressed=#ebbcba
```

just change the hex to any color you like, or see the colors section of the [styling guide](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/tree/main?tab=readme-ov-file#colors) for more info :)

Let me know if you need anything else!

**Comment by miomate** [comment]
Thank you!
