### ISSUE TITLE
Win Button can't be activate again (gradient nor image) in RosePine theme?

### ISSUE THREAD

**Issue by miomate** [ramensoftware/windows-11-taskbar-styling-guide#139]
Hello,

I am using RosePine and I am not able to activate the windows button, which is not available with this theme.

I found this:

> It removes the start button and the network icon. If you need these, add them
  using the
  [guide](https://github.com/ramensoftware/windows-11-taskbar-styling-guide).
  
  This guide explains how to remove the button, how to set image or gradient. I tried following with no luck:

Gradient
Taskbar.TaskListButtonPanel > Border#BackgroundElement
Taskbar.TaskListLabeledButtonPanel > Border#BackgroundElement
Style: Background:=<LinearGradientBrush StartPoint="0.5,0" EndPoint="0.5,1"><GradientStop Offset="0" Color="DodgerBlue"/><GradientStop Offset="1" Color="Yellow"/></LinearGradientBrush>

Image
Taskbar.ExperienceToggleButton#LaunchListButton[AutomationProperties.AutomationId=StartButton] > Taskbar.TaskListButtonPanel > Border#BackgroundElement
Background:=<ImageBrush Stretch="Uniform" ImageSource="https://imgur.com/lEvZStx" />

Maybe I only need this: Visibility=Collapsed but what is the opposite of collapsed?

Thank you for the help.

**Comment by bbmaster123** [comment]
you have to first set visibility to `Visibility=Visible` 
it will then show up in the rosepine theme

for background color/image, you don't have anything set, so you'll need to set something there.
have you looked at the "finding targets" and "colors" section of the styling guide? I believe those sections will help :)

**Comment by bartdorsey** [comment]
This doesn't work for me either, I tried setting it to Visibility=Visible and it doesn't work.

**Comment by bartdorsey** [comment]
I took a guess and figured it out, You are putting Visibility.Visible on the background, when you need to change it on the start button itself by using this Target

```Taskbar.ExperienceToggleButton#LaunchListButton[AutomationProperties.AutomationId=StartButton]```

**Comment by bbmaster123** [comment]
@bartdorsey ah yea thanks, good catch, the correct target needs to of course be selected. The screenshot was from another thread and was intended just to show that its possible to do. I should have communicated better.

**Comment by miomate** [comment]
Thank you very much, both of you.

For some reason I was in the "Recourse variables" category, therefore nothing worked, I had to work in the "Control styles" category. Stupid mistake.

**Comment by miomate** [comment]
Thank you very much, both of you.

For some reason I was in the "Recourse variables" category, therefore nothing worked, I had to work in the "Control styles" category. Stupid mistake.
