### ISSUE TITLE
Adjusting ProgressBar style - not quite working

### ISSUE THREAD

**Issue by rboxman** [ramensoftware/windows-11-taskbar-styling-guide#19]
Hello, with some help from #12, I've been running with a taskbar indicator of 2px thickness and shifted down a few pixels.  However, I haven't been able to correctly modify the ProgressBar portion it seems. It's not obeying the thickness or curve radius settings I've attempted.

Is it possible for the progress bar on the right here to match the thickness and radius of the line of the left?
![too-large-progressbar](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/121978576/e17196c9-7b76-4758-9870-f0a34f59016b)

My config looks as follows:
```
{
  "controlStyles[0].target": "taskbar:TaskListLabeledButtonPanel@RunningIndicatorStates > Rectangle#RunningIndicator",
  "controlStyles[0].styles[0]": "Transform3D:=<CompositeTransform3D CenterX=\"80\" TranslateY=\"3\" />",
  "controlStyles[0].styles[1]": "Height=2",
  "controlStyles[0].styles[2]": "Height@ActiveRunningIndicator=2",
  "controlStyles[0].styles[3]": "Height@InactiveRunningIndicator=2",
  "controlStyles[0].styles[4]": "Height@RequestingAttentionRunningIndicator=2",

  "controlStyles[1].target": "taskbar:TaskListLabeledButtonPanel@RunningIndicatorStates > muxc:ProgressBar#ProgressIndicator",
  "controlStyles[1].styles[0]": "Transform3D:=<CompositeTransform3D CenterX=\"80\" TranslateY=\"3\" />",
  "controlStyles[1].styles[1]": "Height=2",

  "resourceVariables[0].variableKey": "TaskListButtonIndicatorMargin",
  "resourceVariables[0].value": "0,0,0,-2",
  "resourceVariables[1].variableKey": "ProgressBarMinHeight",
  "resourceVariables[1].value": "2",
  "resourceVariables[2].variableKey": "ProgressBarCornerRadius",
  "resourceVariables[2].value": "1",

  "theme": ""
}
```

**Comment by m417z** [comment]
If you'd look with UWPSpy, you'd see that there are more nested elements involved with the progress bar. Adding the following seems to be enough:

```
taskbar:TaskListLabeledButtonPanel@RunningIndicatorStates > muxc:ProgressBar#ProgressIndicator > Grid#LayoutRoot
```

```
Height=2
```

**Comment by rboxman** [comment]
That seems to have done it! Thank you.

**Comment by regs01** [comment]
Is it possible to make it the way it was in Windows 7 and Windows 10? Using full background.

**Comment by m417z** [comment]
@regs01 it was discussed here: https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/68.
