### ISSUE TITLE
Windows 11 Taskbar Styler Customization Idea

### ISSUE THREAD

**Issue by KevBrit** [ramensoftware/windows-11-taskbar-styling-guide#2]
Hi Michael, I set my taskbar to "transparent," which worked perfectly.  However, there is a 1-pixel horizontal line that spans above the taskbar.  Wouldn't it look cleaner if there were a way to disguise/remove that horizontal line?  Just an idea ...

Love your stuff !!!

![Windhawk](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/38546819/a6c0c0db-ccf2-4533-a42c-47b10b915437)

**Comment by m417z** [comment]
You can hide it with target:
```
Rectangle#BackgroundStroke
```
Style:
```
Visibility=Collapsed
```

**Comment by m417z** [comment]
I added it to the guide.

**Comment by KevBrit** [comment]
... and just like that, the horizontal line is gone and taskbar looking clean!

Oh, and thanks for releasing 1.2.2 to fix that crash loop I was experiencing in previous rev after setting taskbar background to transparent.  Every time I started my computer, I had to set Windhawk to Safe Mode, turn off Win11 Taskbar Styler, exit Safe Mode, restart Explorer in Task Manager, then turn Win11 Taskbar Styler back on.  Was fine for day until I restarted computer.  I'll never know how you can find and fix these things so fast, nice work.

**Comment by KevBrit** [comment]
… and just like that, the horizontal border is gone and taskbar looking clean!

Also, thanks for updating to 1.2.2 to fix that crash loop I was experiencing after setting taskbar to transparent.
