### ISSUE TITLE
Customizing tasks background: Differentiate tasks state (not opened, flashing, minimized, hover)

### ISSUE THREAD

**Issue by Nojevah** [ramensoftware/windows-11-taskbar-styling-guide#3]
Thanks for the nice guide, taskbar is always improving.

I know we can change background of tasks thanks to
Target: taskbar:TaskListLabeledButtonPanel > Border#BackgroundElement
(style: Background=#5000F000)

Is there a way to have different background for
1) Pinned apps not opened
2) Tasks which have an alert (called "RequestingAttentionRunningIndicator" for Runningindicator element)
3) All other normal windows (if possible, distinguish minimized tasks but maybe it's not possible)
4) And all these without losing "hover" effect
?

**Comment by m417z** [comment]
From the visual states listed in the XAML file which is linked in the mod description, you can find the following visual state group for `taskbar:TaskListButtonPanel`:
```
CommonStates
```
Which has the following states:
```
RequestingAttentionMultiWindowSharingPressed
RequestingAttentionMultiWindowSharingPointerOver
RequestingAttentionMultiWindowSharing
RequestingAttentionMultiPressed
RequestingAttentionMultiPointerOver
RequestingAttentionMulti
MultiWindowSharingPressed
MultiWindowSharingPointerOver
MultiWindowSharingActive
MultiWindowSharingNormal
MultiWindowPressed
MultiWindowPointerOver
MultiWindowActive
MultiWindowNormal
ActivePressed
ActivePointerOver
WindowSharingRequestingAttentionPressed
WindowSharingRequestingAttentionPointerOver
WindowSharingRequestingAttention
RequestingAttentionPressed
RequestingAttentionPointerOver
RequestingAttention
WindowSharingActivePressed
WindowSharingActivePointerOver
WindowSharingActive
WindowSharingPressed
WindowSharingPointerOver
WindowSharingNormal
ActiveNormal
InactivePressed
InactivePointerOver
InactiveNormal
```
1. Perhaps inactive means pinned and active means running.
2. Everything with `RequestingAttention`.
3. I assume it's not possible to distinguish minimized items.
4. You have `PointerOver`.

That's a quick reply, I didn't have time to test it yet. Try it and let me know whether it addresses you questions.

**Comment by Nojevah** [comment]
I've tried Background@ActiveNormal=#5000F000 and a lot of them, but it doesn't work (whereas Background=#5000F000 works).
Maybe it doesn't apply with this target (taskbar:TaskListLabeledButtonPanel > Border#BackgroundElement).

**Comment by m417z** [comment]
Yes, you must specify the visual state group, `CommonStates`, in the target. Something like:
```
taskbar:TaskListLabeledButtonPanel@CommonStates > Border#BackgroundElement
```
Without specifying the visual state group in the target, adding a visual state in the styles has no effect.

**Comment by Nojevah** [comment]
Thanks for the info. Unfortunately, with this method, style is applied as soon as I save it in Windhawk, it does not consider states (like if I didn't put @RequestingAttention in the line).

**Comment by m417z** [comment]
Post you target and the list of styles.

**Comment by Nojevah** [comment]
I use:
Target: taskbar:TaskListLabeledButtonPanel@RequestingAttention > Border#BackgroundElement
Style: Background=#a000F000

And I end up with:
![image](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/7541249/acb99ae7-0005-4d8f-ae6a-45c2d94b1445)

Whereas I should have:
![image](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/7541249/e4ec54d6-7304-4ffa-bc0b-f0919b342f52)
And only windows with alert (or other CommonStates I've tried) should be displayed differently.

**Comment by m417z** [comment]
Try this:
Target: `taskbar:TaskListLabeledButtonPanel@CommonStates > Border#BackgroundElement`
Style: `Background@RequestingAttention=#a000F000`

`CommonStates` is the visual state group. `RequestingAttention` is the visual state.

**Comment by Nojevah** [comment]
Thank you, it works with your solution. Some example:

Target: taskbar:TaskListLabeledButtonPanel@CommonStates > Border#BackgroundElement
Styles:
Background@ActiveNormal=#3000ff00
Background@ActivePointerOver=#5000ff00
Background@ActivePressed=#5000ff00
Background@RequestingAttention=#80ff0000
Background@RequestingAttentionPointerOver=#a0ff0000
Background@InactivePointerOver=#30ffffff
Background@InactiveNormal=#10ffffff

RequestingAttention is for flashing windows like anticipated.
Inactive is for background for all tasks... and pinned apps (unfortunately)
Active is for focused app.

It works very well.

I've tried to search for "hover" for SystemTray icons, but I didn't manage to succeed, despite spending hours on UWPSpy and SystemTrayResources.xbf. If you find something, I'm interested, but I guess it's another issue so I'll open it in the future if necessary.

**Comment by Imold** [comment]
> I've tried to search for "hover" for SystemTray icons, but I didn't manage to succeed, despite spending hours on UWPSpy and SystemTrayResources.xbf. If you find something, I'm interested, but I guess it's another issue so I'll open it in the future if necessary.

For the ControlCenterButton and Clock/NotificationCenterButton

Target:
systemtray:OmniButton > Grid@CommonStates > Border#BackgroundBorder

Styles
Background@Normal=
Background@PointerOver=
Background@Pressed=
Background@Checked=
Background@CheckedPointerOver=
Background@CheckedPressed=
Background@Disabled=

Unfortunately the visual state groups for everything else in the SystemTray is unnamed making them impossible to style based on visual state, unless support is added for unnamed visual state groups.

**Comment by m417z** [comment]
@Imold interesting, I didn't know that there are unnamed visual state groups. Can you try forking the mod and removing the following two lines:

```cpp
                    throw std::runtime_error(
                        "Bad target syntax, empty visual state group");
```

https://github.com/ramensoftware/windhawk-mods/blob/f80c31b2a02a858d585c01b85fb3d5d5f1789555/mods/windows-11-taskbar-styler.wh.cpp#L2014-L2015

Then you should be able to use an empty visual state group in the target, for example:
```
systemtray:OmniButton > Grid@ > Border#BackgroundBorder
```

Let me know whether it works, if it is, I'll make the change in the mod for the next version.

**Comment by Imold** [comment]
@m417z It works. :)

**Comment by Nojevah** [comment]
I will put a screenshot if someone had questions, but thanks to WH, we can do some things that were only possible with Litestep shell back in the old time...
![image](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/7541249/8bf81494-e588-4bdb-8a87-487d08cba9ce)

In this screenshot, I have what looks like a bug/limitation: **"UWPSpy" tasks don't have a background** despite having a generic "Background" for backup in case I would enter in no "CommonStates". Why UWPSpy only ? Can't tell, these are the only tasks for which I noticed this behavior.
The "RequestionAttention" windows don't have background either during flashing, but it is not really problematic, it may be a Windows way of flashing which is especially noticeable because I have a transparent taskbar.

Here is the code concerning this item:
Target: taskbar:TaskListLabeledButtonPanel@CommonStates > Border#BackgroundElement
Styles:
Background=#df002020
Background@InactiveNormal=#df002020
Background@InactivePointerOver=#ff004040
Background@InactivePressed=#ff004040
Background@ActiveNormal=#ef004020
Background@ActivePointerOver=#ff007020
Background@ActivePressed=#ff007020
Background@RequestingAttention=#ff900000
Background@RequestingAttentionPointerOver=#ffb00000
Background@RequestingAttentionPressed=#ffb00000

For systray, I have nothing particular, just the "hover" which works well (but needs generic background to avoid a visual glitch).
Target: SystemTray.NotifyIconView > Grid@ > Border#BackgroundBorder
Styles:
Background@PointerOver=#ff006060
Background=#00000000

Here are my complete settings in case some would be interested.
[PL_W11_Taskbar_Styler_Custom.zip](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/files/13805654/PL_W11_Taskbar_Styler_Custom.zip)

**Comment by m417z** [comment]
> In this screenshot, I have what looks like a bug/limitation: **"UWPSpy" tasks don't have a background** despite having a generic "Background" for backup in case I would enter in no "CommonStates". Why UWPSpy only ?

There's a known limitation: UWPSpy and the mod conflict with each other, and when one of them is activated, the other stops receiving notifications about elements. Perhaps that's what causes the issue. Try restarting explorer, and let me know if you see it in a session in which UWPSpy wasn't used.

Regarding the settings, thanks, it's cool but I think it's too specific for a theme entry. Still, somebody who stumbles upon it here may find it useful.

**Comment by Nojevah** [comment]
OK, thanks for information, like I said, I only saw it with UWPSpy so I'm OK with the explanation.
And yes, I've just put my settings here for people which would end up here by a search engine.

**Comment by Nojevah** [comment]
OK, thanks for information, like I said, I only saw it with UWPSpy so I'm OK with the explanation.
And yes, I've just put my settings here for people which would end up here by a search engine.
