### ISSUE TITLE
Missing customization: Edit Languages area (touch keyboard and IME selector, system tray) button width individually.

### ISSUE THREAD

**Issue by IcekingJason** [ramensoftware/windows-11-taskbar-styling-guide#30]
I'm trying to customize the system tray. I‘d like to reduce the size of the touch keyboard buttons and the IME switcher buttons in this group without impacting the icons, aiming for a more compact layout. Thanks！
<img width="269" alt="屏幕截图 2024-06-08 004344" src="https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/172054977/af560182-dc1d-4868-9a3c-664419b16ca9">
<img width="269" alt="屏幕截图 2024-06-08 004354" src="https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/172054977/ac016b76-6271-45a0-a147-7d7819488f11">

**Comment by m417z** [comment]
Some of it was discussed here:
https://github.com/ramensoftware/windhawk-mods/issues/506#issuecomment-2080285612
