### ISSUE TITLE
Start Button Location

### ISSUE THREAD

**Issue by LeviPumarlo** [ramensoftware/windows-11-taskbar-styling-guide#33]
Hi, I am wondering if you could add a new customization, or help me with an existing one. I would like to be able to move the start button to the left of my taskbar, while keeping the icons in the center. 

(OS: Windows 11 Pro) 
I am using the windows 11 taskbar with your Windhawk mod, along with ExplorerPatcher for getting the windows 10 start menu, and I am unaware of any potential compatibility issues or qwerks that could arise from doing this. 

Any help with this particular situation would be very much appreciated.

Thanks,
Levi

**Comment by m417z** [comment]
See https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/10.

**Comment by m417z** [comment]
I created a mod for placing the start button on the left: [Start button always on the left](https://windhawk.net/mods/taskbar-start-button-position).
It has limitations (see the mod description), but generally it works.

![image](https://github.com/user-attachments/assets/03dd0de3-c390-4f45-a83d-c800ac98c9ac)
