### ISSUE TITLE
Windows explorer restarting

### ISSUE THREAD

**Issue by vjaykrsna** [ramensoftware/windows-11-taskbar-styling-guide#34]
When selecting bubble theme and saving the config, the explorer.exe gets stuck on the restarting loop.
Latest Windows 11 developer preview.

**Comment by m417z** [comment]
Are you using a search button that looks like this?

![image](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/4129781/644d9ab9-ac64-4be0-b888-bdcbf789b644)

If so, I also encountered this problem, and it seems to only happen with this search button. Changing its style in the taskbar settings seems to fix it. I'll fix the crash for this button too in the next update of the mod.

**Comment by m417z** [comment]
If the issue that I mentioned is what you experienced, it should be fixed in Windows 11 Taskbar Styler v1.3.5. If not, please let me know and provide more details about the crash.

**Comment by vjaykrsna** [comment]
Yeah it's fixed now.
Thanks buddy.
The bubble design looks pretty 😍.
