### ISSUE TITLE
Background won't change

### ISSUE THREAD

**Issue by kennybruhbruh** [ramensoftware/windows-11-taskbar-styling-guide#37]
Hi, I have a problem with the background of the taskbar, it doesn't change no matter what I type in `Target`

![image](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/105291931/6829bcab-1322-497c-8d9a-b269908dafce)

**Comment by bbmaster123** [comment]
put the name of the element in target. you can get this from uwpspy.
like this for example:

```
Target: 
Rectangle#BackgroundFill

Style: 
Fill=Transparent
```
also keep in mind `<>` insn't part of the style, just put the color or hex code to start with, and it should work
let me know if you need more help!

**Comment by kennybruhbruh** [comment]
> put the name of the element in target. you can get this from uwpspy. like this for example:
> 
> ```
> Target: 
> Rectangle#BackgroundFill
> 
> Style: 
> Fill=Transparent
> ```
> 
> also keep in mind `<>` insn't part of the style, just put the color or hex code to start with, and it should work let me know if you need more help!

Thanks for the quick answer!
Got it now, works great but one small issue, do you know how to get rid of the solid line separating the taskbar?
![image](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/105291931/5ff7d700-c1af-4bf8-bd82-796668d317e4)

**Comment by bbmaster123** [comment]
hmmm thanks for bring that to my attention! I see that's not included in the guide, I'll add that in. We obviously can't include every single customization that's possible, but the background stroke is a pretty common one.


you can hide it by targeting Rectangle#BackgroundStroke with either Fill=Transparent, or Visibility=Collapsed, either will work

**Comment by m417z** [comment]
Actually, it's mentioned here:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide?tab=readme-ov-file#taskbar-border

**Comment by bbmaster123** [comment]
@m417z 
@kennybruhbruh 
ah my mistake, ignore me!
