### ISSUE TITLE
Windows button to the left while the programs are in the middle

### ISSUE THREAD

**Issue by zarbokbence** [ramensoftware/windows-11-taskbar-styling-guide#39]
would it be possible to put the Windows button to the left while the programs are in the middle just like in startallback?

**Comment by bbmaster123** [comment]
there isn't currently a perfect way to do this in taskbar styler.

When the taskbar is left aligned you can move the pinned/running apps to the right, but it leaves a large space. When its set to center, the start button moves around depending how many apps are opened, and if you move it to the left corner, it will go off screen with lots of apps on the taskbar.

see [#679](https://github.com/ramensoftware/windhawk-mods/discussions/679)

**Comment by m417z** [comment]
I created a mod for placing the start button on the left: [Start button always on the left](https://windhawk.net/mods/taskbar-start-button-position).
It has limitations (see the mod description), but generally it works.

![image](https://github.com/user-attachments/assets/03dd0de3-c390-4f45-a83d-c800ac98c9ac)
