### ISSUE TITLE
There doesn't seem to be a way to customize the "squircle" theme's elements' background.

### ISSUE THREAD

**Issue by unjaks** [ramensoftware/windows-11-taskbar-styling-guide#41]
Would be great if we could customize the elements' background, for I, personally, don't enjoy the overly transparent view. Everything else is good, very good.
![image](https://github.com/user-attachments/assets/ae62a127-3f4f-44d9-83f6-6800525c4116)
(Being able to edit the margin would be good too)

**Comment by bbmaster123** [comment]
you should be able to set:
```
Target: Rectangle#BackgroundFill
Style: Background=color/hex/brush
```

is that not working for you? If not send you config, debug log (both in advanced), and double check that target isn't set to transparent elsewhere, say in a second forked version of the styler mod, for example

**Comment by unjaks** [comment]
> you should be able to set:
> 
> ```
> Target: Rectangle#BackgroundFill
> Style: Background=color/hex/brush
> ```
> 
> is that not working for you? If not send you config, debug log (both in advanced), and double check that target isn't set to transparent elsewhere, say in a second forked version of the styler mod, for example

this only changes the background of taskbar, but not the elements inside of it

**Comment by bbmaster123** [comment]
oh I'm sorry, that's what I thought you meant, I'm sure you can see why!
which element/elements did you want to change? all? If you don't know what the element is called, could you send a pic with a colored outline or an arrow pointing to it?

we just need to find which element you want to target and then set whatever color at whatever opacity level you like :)

**Comment by unjaks** [comment]
> oh I'm sorry, that's what I thought you meant, I'm sure you can see why! which element/elements did you want to change? all? If you don't know what the element is called, could you send a pic with a colored outline or an arrow pointing to it?
> 
> we just need to find which element you want to target and then set whatever color at whatever opacity level you like :)

yeah, all. only changing one element would look weird

**Comment by bbmaster123** [comment]
styling all elements will require multiple targets, as there isn't one parameter that changes all the colors at once.
for example:
```
 taskbar:TaskListButtonPanel 
 taskbar:TaskListLabeledButtonPanel 
```
will target the pinned/running apps

 ```
 Taskbar.ExperienceToggleButton
 ```
will target the experience buttons (start, task view, copilot etc)

 ```
Grid#SystemTrayFrameGrid
 ```
will target just the tray area

```
Windows.UI.Xaml.Controls.Grid#OverflowRootGrid
```
will target the tray overflow flyout. 

then you can set any of these, for example:
```
Background=Red
Background=#FF0000 (solid color)
Background=#BBFF0000 (transparency)
Background:=<AcrylicBrush TintColor="Red" TintOpacity="0.5" Opacity="1" /> (Red Acrylic)
```

If you need the target name of an element, use UWPSpy and go down the visual tree.

that should get you most of if not all the way there, but if there are further specific elements you are having trouble with, or any other issues, let me know and I'll do my best to help :)

**Comment by unjaks** [comment]
this too didn't help, but I don't want to take any more of anyone's time, so I'll just do a research of my own. thank you for the attempted help, it was pretty close! you're a good person.
