### ISSUE TITLE
Hide the language button

### ISSUE THREAD

**Issue by simonsergepasi** [ramensoftware/windows-11-taskbar-styling-guide#45]
Is there any target to hide the language button?
![image](https://github.com/user-attachments/assets/e8351792-e9dc-4b27-93fb-2d84bff9de5d)
I've tried with target SystemTray.LanguageTextIconContent, style Visibility=collapsed but this leaves an empty space
![image](https://github.com/user-attachments/assets/a257290c-a6b9-4bea-99dc-9db2553a0a55)

**Comment by bbmaster123** [comment]
it should be SystemTray.Stack#NonActivatableStack
no empty space for me

**Comment by simonsergepasi** [comment]
that's it, thank you 🥰

**Comment by simonsergepasi** [comment]
PS OK UWPSpy shows the target path I'll remember it
![image](https://github.com/user-attachments/assets/dfac7bdf-bb64-432c-ad9d-ce5eb3de9231)
