### ISSUE TITLE
[windows-11-taskbar-styler] mod has a bug in new version

### ISSUE THREAD

**Issue by crazy-zxx** [ramensoftware/windows-11-taskbar-styling-guide#46]
https://github.com/ramensoftware/windhawk-mods/blob/b16412c8ab6de3303ecb179ddcb39a2fe8b28e25/mods/windows-11-taskbar-styler.wh.cpp#L45-L47

In the **_1.3.6_** version of the **_Windows-11-Taskbar-Styler_** module, the theme of **_Translucenttaskbar_** cannot be rendered rightly , making the taskbar show a **_black background_**! 

This theme can be rendered rightly in version 1.3.5!

**Comment by m417z** [comment]
@Undisputed00x made a change to the theme which was only supposed to be relevant when BatterySaver is enabled:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide/pull/38
Can you post screenshots before and after that change?

**Comment by Undisputed00x** [comment]
@crazy-zxx @m417z Mod after update works as intended on my laptop, when batterysaver is on instead of rendering a transparent taskbar now the background has a pitch black color


<details>
<summary>

### BatterySaver Off
</summary>
<p>

<img width="959" alt="Screenshot 2024-07-20 140300" src="https://github.com/user-attachments/assets/5f54b528-f7e5-4931-9be6-befd4ac77477">
</p>
</details>


<details>
<summary>

### BatterSaver On (Before update)
</summary>
<p>


<img width="959" alt="Screenshot 2024-07-20 141910" src="https://github.com/user-attachments/assets/84ae643b-5271-49d2-af07-023d81228a89">
</p>
</details> 


<details>
<summary>

### BatterySaver On (After update)
</summary>
<p>

<img width="959" alt="Screenshot 2024-07-20 140331" src="https://github.com/user-attachments/assets/a2263358-ed44-45e8-b790-d7f356b8c1a2">
</p>
</details>

**Comment by NJinsei** [comment]
Also the squircle theme is also not rendering correctly, even after restarting explorer process.
After Update:
![image](https://github.com/user-attachments/assets/07ffa535-7043-49c2-8808-bf9119535fed)
Before Update:
![image](https://github.com/user-attachments/assets/cde681b4-aba3-4aee-942d-d1f2288330da)

**Comment by m417z** [comment]
> Also the squircle theme is also not rendering correctly

Likely due to these updates:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide/pull/35

@AsvnDG @bbmaster123 any idea?

For now you can grab the previous configuration and set it manually:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide/blob/e8f3b40da029ed410eba940d2b0f6e7ce6daa362/Themes/Squircle/README.md

**Comment by bbmaster123** [comment]
@m417z 
@crazy-zxx 

Yes TranslucentTaskbar is working as intended on my end as well

as for Squircle, I can reproduce this by changing taskbar labels mod from full width indicators to either of the centered indicators.

Also keep in mind the updated theme has some other fairly significant changes, most likely one of the styles that had been removed had also forced the indicators to be full width in the styler mod, meaning it didn't matter what was set in the labels mod before the theme was updated.

We could add that style back in, or we can add one more note at the top of the readme saying to choose full width indicators with this theme.

**Comment by crazy-zxx** [comment]
I don't know what caused this problem.

However, because the power mode used by my laptop, the BatterySaver mode cannot be turned on, so it cannot try the effect of the setting.


Before update
<details>
<summary>TranslucentTaskbar</summary>

![image](https://github.com/user-attachments/assets/85fa996d-06a4-4951-a5d5-0a6374a6147a)

</details>
<details>
<summary>Squircle</summary>

![image](https://github.com/user-attachments/assets/39faa407-b10c-45ed-9699-f9719de268de)

</details>

After update：

<details>
<summary> TranslucentTaskbar </summary>

![image](https://github.com/user-attachments/assets/70888469-603e-4bae-a930-62fc62031798)
</details>

<details>
<summary>  Squircle </summary> 

![image](https://github.com/user-attachments/assets/8ae44d81-e890-42b5-923d-ed52e8418b9e)
</details>


The module I installed is as follows. I don't know if this problem may be caused by conflict between some modules?

<details>
<summary>  installed mods </summary> 

![image](https://github.com/user-attachments/assets/1e820474-20e6-48be-91e8-78ed4cbd035b)

</details>


And the two themes above （TranslucentTaskbar and Squircle） will have an extremely similar rendering effect on my computer. I thought something was wrong.

**Comment by bbmaster123** [comment]
In regards to the translucent taskbar, the author added FallbackColor="FF000000" in their update, but the author of squircle didn't, so their behavior differs. You can always override the style with your own ie FallbackColor=Transparent if you like.

I don't own a laptop and I am unable to get my vm to activate the fallback color in power saver mode so I think its actually triggered by low battery mode or something? not sure, but anyhow, I can thankfully assure you its not a conflict with other mods.

I hope that clears some of the confusion! :)

**Comment by gilnett** [comment]
For Rose Spine, I just thought it wasn't normal to be without the Start button. For Squircle, I don't have any circles anymore. And for TranslucentTaskbar, it's my fault; the battery saver was enabled.

**Comment by crazy-zxx** [comment]
> In regards to the translucent taskbar, the author added FallbackColor="#FF000000" in their update, but the author of squircle didn't, so their behavior differs. You can always override the style with your own ie FallbackColor=Transparent if you like.关于半透明任务栏，作者在他们的更新中添加了 FallbackColor=“#FF000000”，但 squircle 的作者没有，因此他们的行为有所不同。如果您愿意，您可以随时使用自己的样式覆盖样式，即 FallbackColor=Transparent 。
> 
> I don't own a laptop and I am unable to get my vm to activate the fallback color in power saver mode so I think its actually triggered by low battery mode or something? not sure, but anyhow, I can thankfully assure you its not a conflict with other mods.我没有笔记本电脑，我无法让我的虚拟机在省电模式下激活回退颜色，所以我认为它实际上是由低电池模式或其他原因触发的？不确定，但无论如何，我可以向你保证，它不会与其他模组发生冲突。
> 
> I hope that clears some of the confusion! :)我希望这能消除一些困惑！:)

Yes!
I adjusted this parameter and found that it caused the rendering of the taskbar on my computer to be incorrect! Thank you.

![image](https://github.com/user-attachments/assets/33b90fc1-ca8a-4970-9e8c-ad26a4fc4f4f)
