### ISSUE TITLE
bug or feature. removed the shadows. added choice in %

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windows-11-taskbar-styling-guide#5]
hi, I don't know if it's a bug or if it's normal but I would like to remove the little shadow line from the code (and I can't do it). I don't know if it's possible so I'm posting it here.

I also leave this idea. Added the possibility of modifying the transparency rate (or color) in % that would be good.

![image_2023-12-21_171826698](https://github.com/ramensoftware/windows-11-taskbar-styling-guide/assets/142233342/e2d2b8a7-d7b8-46cd-b16d-1bd0b0b918ec)

**Comment by m417z** [comment]
You can do it, it was requested recently and was added to the guide, see https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/2#issuecomment-1865843034.

> I also leave this idea. Added the possibility of modifying the transparency rate (or color) in % that would be good.

The mod follows the UWP XAML syntax:
https://learn.microsoft.com/en-us/uwp/api/windows.ui.color?view=winrt-22621
It is possible to set the transparency. It's also mentioned in the guide.
