### ISSUE TITLE
Move Taskbar Indicator

### ISSUE THREAD

**Issue by Spider19996** [ramensoftware/windows-11-taskbar-styling-guide#6]
Hey Guys,

just wanted to share something: There is the Mod "Taskbar height and icon size" and if you make the taskbar to small the Indicator moves behind the Icon. This can be fixed with

**Target:** _taskbar:TaskListLabeledButtonPanel@RunningIndicatorStates > Rectangle#RunningIndicator_

**Default Style**: _Margin=0,0,0,2_

0,0,0,2 means:
First 0 = - or + moves left or right
Second and Third = I don't know
Last 2 = - or + moves up and down

My configuration:
**Style:** _Margin=0,0,0,-4

Maybe this can be integrated into the Taskbar Mod too, since this is causing the actual problem.

**Comment by m417z** [comment]
Your solution is likely to break the layout when there are too many items on the taskbar. I'm copying my comment from #12:

> `Margin=0,0,0,-1` doesn't work as it resets the left margin to zero at all times, and this value varies to place the indicator in the correct location. [...] `CompositeTransform3D` can be used to move the indicator to a lower position as following:
> `Transform3D:=<CompositeTransform3D TranslateY="1" />`

**Comment by Spider19996** [comment]
Thank you for your answers. Unfortunately, I'm not a programmer and understand very little about what I'm changing. For me, the ready-made mods that you can activate are actually very important so that nothing breaks. However, I haven't noticed any errors yet.

I will close this issue, as there is another one anyway.

**Comment by m417z** [comment]
I understand, but it's better to have a complex solution than not having a solution at all.
