### ISSUE TITLE
How to make search bar rectangular

### ISSUE THREAD

**Issue by revreys** [ramensoftware/windows-11-taskbar-styling-guide#66]
Question is the title. How?

**Comment by bbmaster123** [comment]
This is for Search Box, not Search Icon and Label:
Target:
`Taskbar.SearchBoxButton#SearchBoxButton > Taskbar.TaskListButtonPanel#ExperienceToggleButtonRootPanel > Border#BackgroundElement`

Style:
`CornerRadius=0`

**Comment by revreys** [comment]
> This is for Search Box, not Search Icon and Label: Target: `Taskbar.SearchBoxButton#SearchBoxButton > Taskbar.TaskListButtonPanel#ExperienceToggleButtonRootPanel > Border#BackgroundElement`
> 
> Style: `CornerRadius=0`

Thank you so much, exactly what i was looking for.

**Comment by revreys** [comment]
how do i force the search bar to stay as a box and never turn into an icon whenever the taskbar has a lot of apps??
