### ISSUE TITLE
Centered Icons with Windows key to the left option addition

### ISSUE THREAD

**Issue by Louis047** [ramensoftware/windows-11-taskbar-styling-guide#70]
As stated in the title, I would like this feature to be added in the future. It could be useful to make the taskbar look like a customized version of polybar/waybar (or whatever you call it) for `Squircle` theme for the mod: `Windows 11 Taskbar Styler`

**Comment by m417z** [comment]
I created a mod for placing the start button on the left: [Start button always on the left](https://windhawk.net/mods/taskbar-start-button-position).
It has limitations (see the mod description), but generally it works.

![image](https://github.com/user-attachments/assets/03dd0de3-c390-4f45-a83d-c800ac98c9ac)
