### ISSUE TITLE
[Need Help] "Show hidden icon" not in Grid#SystemTrayFrameGrid

### ISSUE THREAD

**Issue by BloodLetters** [ramensoftware/windows-11-taskbar-styling-guide#78]
![image](https://github.com/user-attachments/assets/68a79d1c-fff9-46e5-a900-9b48000e3f98)
How to make all tray items can in inside Grid? can someone gimme some sample
i using win 22h2 and acrylic and transparent effect not apply to taskbar

**Comment by bbmaster123** [comment]
I'm not 100% sure what you're asking, sorry, but if you were looking to have tray icons automatically appear in the tray area without being hidden in the overflow, you still need to do that in the settings app under Personalization > Taskbar

If you are asking how to modify the icons in the overflow, the target is `Windows.UI.Xaml.Controls.Grid#OverflowRootGrid`
If you wanted to adjust the up arrow, the target is `systemtray:ChevronIconView`

If you aren't seeing transparency effects, please first make sure that Transparency Effects are turned on in Settings > Personalization > Colors

cheers

**Comment by BloodLetters** [comment]
> I'm not 100% sure what you're asking, sorry, but if you were looking to have tray icons automatically appear in the tray area without being hidden in the overflow, you still need to do that in the settings app under Personalization > Taskbar
> 
> If you are asking how to modify the icons in the overflow, the target is `Windows.UI.Xaml.Controls.Grid#OverflowRootGrid` If you wanted to adjust the up arrow, the target is `systemtray:ChevronIconView`
> 
> If you aren't seeing transparency effects, please first make sure that Transparency Effects are turned on in Settings > Personalization > Colors
> 
> cheers

![image](https://github.com/user-attachments/assets/a62f285a-192e-4fce-8a7a-e913c48ce6fb)
The one I have with the upward arrow is not included in the background. how can I insert the arrow into the background? the example above

**Comment by bbmaster123** [comment]
ah I see now, that is strange. did you manually set the width of the tray area's background element? If you send your code, I'd be happy to take a look!

and as for transparency, does it work when windhawk is disabled?

**Comment by BloodLetters** [comment]
> ah I see now, that is strange. did you manually set the width of the tray area's background element? If you send your code, I'd be happy to take a look!
> 
> and as for transparency, does it work when windhawk is disabled?

idk i use dots from here [Here](https://www.reddit.com/r/desktops/comments/1dna90y/simple_plain_desktop/#lightbox)

Here the code:
`{"controlStyles[0].target":"Rectangle#BackgroundFill","controlStyles[0].styles[0]":"Fill=Transparent","controlStyles[1].target":"Taskbar.TaskListLabeledButtonPanel@RunningIndicatorStates > Border#BackgroundElement","controlStyles[1].styles[0]":"Background:=<AcrylicBrush BackgroundSource=\"Backdrop\" TintColor=\"Black\" TintOpacity=\"0.6\" />","controlStyles[1].styles[1]":"CornerRadius=5","controlStyles[1].styles[2]":"Background@NoRunningIndicator:=<AcrylicBrush BackgroundSource=\"Backdrop\" TintColor=\"Black\" TintOpacity=\"0.15\" />","controlStyles[2].target":"Taskbar.TaskListButtonPanel@CommonStates > Border#BackgroundElement","controlStyles[2].styles[0]":"Background:=<AcrylicBrush BackgroundSource=\"Backdrop\" TintColor=\"Black\" TintOpacity=\"0.6\" />","controlStyles[2].styles[1]":"CornerRadius=5","controlStyles[2].styles[2]":"Background@ActivePointerOver=#B3202020","controlStyles[2].styles[3]":"Background@InactivePointerOver=#B3202020","controlStyles[2].styles[4]":"Background@ActivePressed=#B3101010","controlStyles[2].styles[5]":"Background@InactivePressed=#B3101010","controlStyles[3].target":"Grid#SystemTrayFrameGrid","controlStyles[3].styles[0]":"Background:=<AcrylicBrush BackgroundSource=\"Backdrop\" TintColor=\"Black\" TintOpacity=\"0.60\" />","controlStyles[3].styles[1]":"CornerRadius=5","controlStyles[3].styles[2]":"Margin=0,5,14,5","controlStyles[3].styles[3]":"Padding=10,0,0,0","controlStyles[4].target":"Taskbar.TaskListLabeledButtonPanel@CommonStates > Rectangle#RunningIndicator","controlStyles[4].styles[0]":"Width=40","controlStyles[4].styles[1]":"Height=40","controlStyles[4].styles[2]":"Stroke@InactivePointerOver=#75A8E6","controlStyles[4].styles[3]":"Stroke@InactivePressed=#7CB1F2","controlStyles[4].styles[4]":"Stroke@ActiveNormal=#5F87B9","controlStyles[4].styles[5]":"Stroke@ActivePointerOver=#75A8E6","controlStyles[4].styles[6]":"Stroke@ActivePressed=#7CB1F2","controlStyles[4].styles[7]":"Fill=Transparent","controlStyles[4].styles[8]":"RadiusX=5","controlStyles[4].styles[9]":"RadiusY=5","controlStyles[4].styles[10]":"StrokeThickness=3","controlStyles[4].styles[11]":"Margin=0","controlStyles[5].target":"TextBlock#TimeInnerTextBlock","controlStyles[5].styles[0]":"Foreground=White","controlStyles[6].target":"TextBlock#DateInnerTextBlock","controlStyles[6].styles[0]":"Foreground=White","controlStyles[7].target":"SystemTray.TextIconContent > Grid > SystemTray.AdaptiveTextBlock#Base > TextBlock","controlStyles[7].styles[0]":"Foreground=White","controlStyles[8].target":"Taskbar.TaskListLabeledButtonPanel > TextBlock#LabelControl","controlStyles[8].styles[0]":"Margin=4,0,0,0","controlStyles[8].styles[1]":"Foreground=White","controlStyles[9].target":"Taskbar.SearchBoxButton","controlStyles[9].styles[0]":"Height=56","controlStyles[9].styles[1]":"Margin=0,-4,0,0","controlStyles[10].target":"TextBlock#SearchBoxTextBlock","controlStyles[10].styles[0]":"Foreground=White","controlStyles[11].target":"Rectangle#BackgroundStroke","controlStyles[11].styles[0]":"Fill=Transparent","controlStyles[12].target":"SystemTray.Stack#ShowDesktopStack","controlStyles[12].styles[0]":"Visibility=Collapsed","controlStyles[10].styles[1]":"FontSize=12"}`

**Comment by bbmaster123** [comment]
can't replicate this on my end. Looks normal for me. You can try adding some padding to left:
Grid#SystemTrayFrameGrid
Padding=35,0,0,0

if transparency works with windhawk disabled, what about with windhawk enabled but all mods disabled? if that works, can you identify which mod is the issue? 
Is taskbar styler causing the transparency issue?
If so, does transparency work with the updated squircle theme that's built into the mod? I assume you're using the older version because you like that one better

**Comment by BloodLetters** [comment]
> can't replicate this on my end. Looks normal for me. You can try adding some padding to left: Grid#SystemTrayFrameGrid Padding=35,0,0,0
> 
> if transparency works with windhawk disabled, what about with windhawk enabled but all mods disabled? if that works, can you identify which mod is the issue? Is taskbar styler causing the transparency issue? If so, does transparency work with the updated squircle theme that's built into the mod? I assume you're using the older version because you like that one better

Looks like the transparency is working, it seems there is a problem with my windows because I am using ghost specter 22h2. so i think i will mark it as solved
