### ISSUE TITLE
Hide Mic active Icon

### ISSUE THREAD

**Issue by Rocker2234** [ramensoftware/windows-11-taskbar-styling-guide#8]
Is it possible to hide the Mic Icon that we get when it's in use. I tried searching it on the file, but I didn't have any luck.

**Comment by Imold** [comment]
`{ "controlStyles[0].target": "SystemTray.Stack#MainStack", "controlStyles[0].styles[0]": "Visibility=Collapsed" }`
Let me guess, you use Voicemeeter.

**Comment by Rocker2234** [comment]
Thankyou, and no I do not use that. It's because of OBS.

**Comment by Imold** [comment]
I just guessed you used Voicemeeter because that's why people were asking for removing the Mic Icon to be added to ExplorerPatcher.
