### ISSUE TITLE
不知道这个是否能做到

### ISSUE THREAD

**Issue by Mcyzv7** [ramensoftware/windows-11-taskbar-styling-guide#91]
在电脑桌面和软件小窗口的时候任务栏是透明的，在软件最大化窗口的时候任务栏是半透明或者亚巧克力的

**Comment by m417z** [comment]
Please use English. I assume you're asking this, see my comment in this issue: https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/85.
